---
- name: download factorio docker compose file
  copy:
    src: factorio-compose.yml
    dest: /root/docker-compose.yml

- name: start the factorio service
  command:
    cmd: docker-compose up -d
    chdir: /root

- name: configure nightly service update
  cron:
    name: updateFactorio
    state: present
    minute: 0
    hour: 4
    job: /usr/local/sbin/docker-compose pull && /usr/local/sbin/docker-compose up -d --force-recreate
