---
all:
  hosts:
    net:
  children:
    proxmox:
      hosts:
        castle01:
          ansible_host: 192.168.86.133
    labInternal:
      hosts:
        factorio:
        minecraft:

  vars:
    ansible_become: yes
