---
- name: download minecraft docker compose file
  copy:
    src: minecraft-compose.yml
    dest: /root/minecraft-compose.yml

- name: start the minecraft service
  become: true
  command:
    cmd: /usr/local/sbin/docker-compose -f minecraft-compose.yml up -d
    chdir: /root

- name: configure nightly service update
  cron:
    name: updateMinecraft
    state: present
    minute: "0"
    hour: "4"
    job: /usr/local/sbin/docker-compose pull && /usr/local/sbin/docker-compose up -f minecraft-compose.yml -d --force-recreate
