---
- name: copy network interfaces configuration
  copy:
    src: interfaces
    dest: /etc/network/interfaces
  register: interfaces

- name: reload network interfaces
  command:
    cmd: ifreload -a
  when: interfaces.changed
