---
- name: check if vm template exists
  stat:
    path: /etc/pve/nodes/{{ pveHost }}/qemu-server/{{ item.templateId }}.conf
  register: template

- name: update existing template base image if it exists
  shell: |
    qm unlink {{ item.templateId }} --idlist virtio0 --force
    qm importdisk {{ item.templateId }} /tmp/{{ templateImage }} local-lvm
  when: updateTemplateImage and template.stat.exists

# TODO: find a way to truly detect if this block is changed
- name: update existing template properties
  shell: |
    qm set {{ item.templateId }} --scsihw virtio-scsi-pci --virtio0 local-lvm:vm-{{ item.templateId }}-disk-0
    qm set {{ item.templateId }} --memory {{ item.memory }} --cores {{ item.cpuCores }} --name {{ item.templateName }}
    qm set {{ item.templateId }} --ipconfig0 ip=dhcp --cicustom "user=local:snippets/vmUserData.yml"
    qm resize {{ item.templateId }} virtio0 {{ item.diskSize }}
  when: template.stat.exists

- name: create template vm
  shell: |
    qm create {{ item.templateId }} --memory {{ item.memory }} --net0 virtio,bridge=vmbr0 --cores {{ item.cpuCores }} -hotplug network,disk,cpu,memory --numa 1 --agent 1 --name {{ item.templateName }} --ostype l26
    qm importdisk {{ item.templateId }} /tmp/{{ templateImage }} local-lvm
    qm set {{ item.templateId }} --scsihw virtio-scsi-pci --virtio0 local-lvm:vm-{{ item.templateId }}-disk-0
    qm set {{ item.templateId }} --ide2 local-lvm:cloudinit
    qm set {{ item.templateId }} --boot c --bootdisk virtio0
    qm set {{ item.templateId }} --serial0 socket
    qm set {{ item.templateId }} --ipconfig0 ip=dhcp --cicustom "user=local:snippets/vmUserData.yml"
    qm set {{ item.templateId }} --onboot 1
    qm resize {{ item.templateId }} virtio0 {{ item.diskSize }}
    qm template {{ item.templateId }}
  when: not template.stat.exists
