# Much of this implementation by Faranoosh: https://gitlab.com/itnoobs-automation/ansible/proxmox-template
---
- name: prepare host for template creation
  include_tasks: prepareHost.yml

- name: create vm templates
  include_tasks: createVmTemplate.yml
  with_items: "{{ templateDetails }}"
# TODO: initialize VMs as needed
# TODO: need to install QEMU guest agent on all new VMs - this role or another?  Somehow put into template?  (apt install qemu-guest-agent && systemctl start qemu-guest-agent)
