---
- name: prepare host for template creation
  include_tasks: prepareHost.yml

- name: create vm templates
  include_tasks: createVmTemplate.yml
  with_items: "{{ templateDetails }}"
# TODO: initialize VMs as needed
