# Much of this implementation by Faranoosh: https://gitlab.com/itnoobs-automation/ansible
---
- name: enable community sources
  apt_repository:
    repo: deb http://download.proxmox.com/debian buster pve-no-subscription
    state: present

- name: disable enterprise sources
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise
    state: absent

- name: update host
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot

- name: reboot if required
  reboot:
  when: reboot.stat.exists

- name: get latest debian checksums
  get_url:
    url: https://cdimage.debian.org/cdimage/openstack/current/SHA256SUMS
    dest: /tmp

- name: find signature for target image
  shell: grep ".*{{ templateImage }}$" /tmp/SHA256SUMS | awk '{print $1}'
  changed_when: false
  register: checksum

- name: get latest debian 10 cloud image and verify against signature
  get_url:
    url: https://cdimage.debian.org/cdimage/openstack/current/{{ templateImage }}
    dest: /tmp/{{ templateImage }}
    checksum: "sha256:{{ checksum.stdout }}"
  register: baseImage

- name: copy public key to host
  copy:
    src: "{{ sshKeyFile }}"
    dest: /tmp/sshkey.pub
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: add ssh key to authorized_keys file
  lineinfile:
    path: /{{ ansible_user }}/.ssh/authorized_keys
    state: present
    line: "{{ lookup('file', sshKeyFile) }}"

- name: copy user data script to host
  template:
    src: vmUserData.yml.j2
    dest: /var/lib/vz/snippets/vmUserData.yml
  vars:
    sshKey: "{{ lookup('file', sshKeyFile) }}"

- name: create vm templates
  include_tasks: createVmTemplate.yml
  with_items: "{{ templateDetails }}"
  vars:
    updateTemplateImage: "{{ baseImage.changed }}"

- name: create vms
  include_tasks: createVm.yml
  with_items: "{{ vmDetails }}"
