version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    environment:
      EULA: "true"
      INIT_MEMORY: "512M"
      MAX_MEMORY: "3G"
    ports:
      - "25565:25565"
    volumes:
      - /backup/minecraft:/data
