version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    container_name: minecraft_server
    environment:
      EULA: "true"
      VERSION: "1.18.1"
      INIT_MEMORY: "512M"
      MAX_MEMORY: "2560M"
      OVERRIDE_SERVER_PROPERTIES: "true"
      SERVER_NAME: "Mushroom Kingdom"
      DIFFICULTY: "normal"
      OVERRIDE_OPS: "true"
      OPS: "davinci28"
      OVERRIDE_WHITELIST: "true"
      WHITELIST: "davinci28,Seezon,wa_lee,mld719"
      MOTD: "The Mushroom Kingdom"
    ports:
      - "25565:25565"
    volumes:
      - /backup/minecraft:/data
