version: "2"
services:
  factorio:
    image: factoriotools/factorio
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /backup/factorio:/factorio
