---
- name: add wireguard apt source
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: install wireguard
  apt:
    name:
      - linux-headers-cloud-amd64
      - wireguard
    state: present

- name: copy wireguard configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0744

- name: enable port forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: enable and start wireguard
  systemd:
    name: wg-quick@wg0
    enabled: true
    state: restarted
    daemon_reload: true
