---
- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot
  listen: reboot
- name: reboot if required
  reboot:
  when: reboot.stat.exists
  listen: reboot
