---
- name: update host
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot

- name: reboot if required
  reboot:
  when: reboot.stat.exists
