---
- name: update host
  apt:
    update_cache: true
    upgrade: safe
    autoremove: yes

- name: install essential packages
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: latest
  loop:
    - sudo
    - unattended-upgrades

- name: enable unattended upgrades
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644

- name: set timezone
  timezone:
    name: America/New_York
# - name: install required packages
#   apt:
#     name:
#       - zip
#     state: present

# - name: check if backup exists in S3
#   command:
#     cmd: aws s3 ls s3://{{ backupS3Bucket }}/{{ inventory_hostname }}.zip
#   register: backupFound
#   failed_when: false
#   changed_when: false

# - name: download backup from S3
#   command:
#     cmd: aws s3 cp s3://{{ backupS3Bucket }}/{{ inventory_hostname }}.zip /tmp/backup.zip
#     creates: /tmp/backup.zip
#   when: backupFound.rc == 0

# - name: restore backup from S3
#   unarchive:
#     src: /tmp/backup.zip
#     dest: /
#     remote_src: yes
#     creates: /backup
#   when: backupFound.rc == 0

# - name: create backup directory if it doesn't already exist
#   file:
#     path: /backup
#     state: directory
#     mode: 0755

# - name: copy backup script to host
#   template:
#     src: backup.j2
#     dest: /usr/local/sbin/backup
#     owner: root
#     group: root
#     mode: 0744

# - name: configure daily backup to S3
#   cron:
#     name: backup
#     state: present
#     minute: 0
#     hour: 3
#     job: backup

# - name: configure backup on shutdown
#   copy:
#     src: backup.service
#     dest: /etc/systemd/system/backup.service
#     owner: root
#     group: root

# - name: reload systemd
#   systemd:
#     name: backup
#     enabled: true
#     state: started
#     daemon_reload: true
