---
- name: update proxmox sources
  import_tasks: setUpProxmoxSources.yml

- name: update host
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: trigger reboot
  command: "true"
  notify: reboot
