---
- name: determine if host is a proxmox host
  stat:
    path: /etc/pve
  register: proxmox_files

- name: enable community sources
  apt_repository:
    repo: deb http://download.proxmox.com/debian buster pve-no-subscription
    state: present

- name: disable enterprise sources
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise
    state: absent
