---
- name: install required packages
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: latest
  loop:
    - curl

- name: set up dynamic DNS for lab domain
  cron:
    name: ddns [{{ item.domain }}]
    state: present
    minute: "*/5"
    job: "curl https://{{ item.googleDomainsUser }}:{{ item.googleDomainsPassword }}@domains.google.com/nic/update?hostname={{ item.domain }} 2>&1 | /usr/bin/logger -t ddns"
  loop: "{{ ddnsEntries }}"
  no_log: true
